import fs from "node:fs/promises"
import path from "node:path"
import { Global } from "@/global"
import { Installation } from "@/installation"
import { Filesystem } from "@/util/filesystem"
import { Log } from "@/util/log"
import { directoryDigest } from "./bundle-format"

type Bundle = {
  SKILL_BUNDLE: string
  SKILL_BUNDLE_DIGEST: string
  SKILL_BUNDLE_FILES: number
  SKILL_BUNDLE_SKILLS: number
}

export namespace BundledSkills {
  const log = Log.create({ service: "bundled-skills" })

  async function generated(): Promise<Bundle | undefined> {
    // @ts-ignore generated by script/generate-skill-bundle.ts during release builds
    return import("./bundled.generated").catch(() => undefined)
  }

  export async function materialize(input: {
    archive: string
    digest: string
    files: number
    skills: number
    cache?: string
  }): Promise<string> {
    if (!/^[a-f0-9]{64}$/.test(input.digest)) throw new Error("Invalid bundled skill digest")
    const base = input.cache ?? path.join(Global.Path.cache, "bundled-skills")
    const root = path.join(base, input.digest)
    const marker = path.join(root, ".openscience-bundle.json")
    const ready = await Bun.file(marker)
      .json()
      .then((value) => value?.digest === input.digest && value?.files === input.files && value?.skills === input.skills)
      .catch(() => false)
    if (ready) return root

    const tmp = path.join(base, `.${input.digest}.${process.pid}.${Date.now()}`)
    await fs.mkdir(base, { recursive: true })
    await fs.rm(tmp, { recursive: true, force: true })
    const bytes = await Bun.file(input.archive).bytes()
    const count = await new Bun.Archive(bytes).extract(tmp)
    if (count < input.files) {
      await fs.rm(tmp, { recursive: true, force: true })
      throw new Error(`Bundled skill archive is incomplete: expected ${input.files} files, extracted ${count}`)
    }
    const digest = await directoryDigest(tmp)
    if (digest !== input.digest) {
      await fs.rm(tmp, { recursive: true, force: true })
      throw new Error(`Bundled skill archive failed verification: expected ${input.digest}, got ${digest}`)
    }

    for await (const script of new Bun.Glob("**/*.{py,sh,js,ts}").scan({ cwd: tmp, absolute: true, onlyFiles: true })) {
      await fs.chmod(script, 0o755).catch(() => {})
    }
    await Bun.write(
      path.join(tmp, ".openscience-bundle.json"),
      JSON.stringify({ digest: input.digest, files: input.files, skills: input.skills }),
    )

    const raced = await Bun.file(marker)
      .json()
      .then((value) => value?.digest === input.digest && value?.files === input.files && value?.skills === input.skills)
      .catch(() => false)
    if (raced) {
      await fs.rm(tmp, { recursive: true, force: true })
      return root
    }

    await fs.rm(root, { recursive: true, force: true })
    await fs.rename(tmp, root)
    return root
  }

  export async function root(): Promise<string | undefined> {
    const local = path.join(import.meta.dir, "../../skills")
    if (Installation.isLocal() && (await Filesystem.isDir(local))) return local

    const bundle = await generated()
    if (!bundle) {
      log.error("compiled release is missing its local skill bundle")
      return
    }

    return materialize({
      archive: bundle.SKILL_BUNDLE,
      digest: bundle.SKILL_BUNDLE_DIGEST,
      files: bundle.SKILL_BUNDLE_FILES,
      skills: bundle.SKILL_BUNDLE_SKILLS,
    })
  }
}
