import fs from "node:fs/promises"
import path from "node:path"
import { Global } from "@/global"
import { Installation } from "@/installation"
import { Filesystem } from "@/util/filesystem"
import { Log } from "@/util/log"
import { directoryDigest } from "./bundle-format"

type Bundle = {
  SKILL_BUNDLE: string
  SKILL_BUNDLE_DIGEST: string
  SKILL_BUNDLE_FILES: number
  SKILL_BUNDLE_SKILLS: number
}

export namespace BundledSkills {
  const log = Log.create({ service: "bundled-skills" })

  async function generated(): Promise<Bundle | undefined> {
    // @ts-ignore generated by script/generate-skill-bundle.ts during release builds
    return import("./bundled.generated").catch(() => undefined)
  }

  type Materialize = { archive: string; digest: string; files: number; skills: number; cache?: string }

  // Every project instance asks for the bundle root as it starts. Sharing one
  // in-flight extraction per target keeps a burst of instances from racing
  // each other's rename; other processes are handled at the rename itself.
  const inflight = new Map<string, Promise<string>>()

  export function materialize(input: Materialize): Promise<string> {
    if (!/^[a-f0-9]{64}$/.test(input.digest)) return Promise.reject(new Error("Invalid bundled skill digest"))
    const base = input.cache ?? path.join(Global.Path.cache, "bundled-skills")
    const key = path.join(base, input.digest)
    const pending = inflight.get(key)
    if (pending) return pending
    const task = extract(input, base).finally(() => inflight.delete(key))
    inflight.set(key, task)
    return task
  }

  async function verified(marker: string, input: Materialize) {
    return Bun.file(marker)
      .json()
      .then((value) => value?.digest === input.digest && value?.files === input.files && value?.skills === input.skills)
      .catch(() => false)
  }

  async function extract(input: Materialize, base: string): Promise<string> {
    const root = path.join(base, input.digest)
    const marker = path.join(root, ".openscience-bundle.json")
    if (await verified(marker, input)) return root

    const tmp = path.join(base, `.${input.digest}.${process.pid}.${Date.now()}`)
    await fs.mkdir(base, { recursive: true })
    await fs.rm(tmp, { recursive: true, force: true })
    const bytes = await Bun.file(input.archive).bytes()
    const count = await new Bun.Archive(bytes).extract(tmp)
    if (count < input.files) {
      await fs.rm(tmp, { recursive: true, force: true })
      throw new Error(`Bundled skill archive is incomplete: expected ${input.files} files, extracted ${count}`)
    }
    const digest = await directoryDigest(tmp)
    if (digest !== input.digest) {
      await fs.rm(tmp, { recursive: true, force: true })
      throw new Error(`Bundled skill archive failed verification: expected ${input.digest}, got ${digest}`)
    }

    for await (const script of new Bun.Glob("**/*.{py,sh,js,ts}").scan({ cwd: tmp, absolute: true, onlyFiles: true })) {
      await fs.chmod(script, 0o755).catch(() => {})
    }
    await Bun.write(
      path.join(tmp, ".openscience-bundle.json"),
      JSON.stringify({ digest: input.digest, files: input.files, skills: input.skills }),
    )

    if (await verified(marker, input)) {
      await fs.rm(tmp, { recursive: true, force: true })
      return root
    }

    await fs.rm(root, { recursive: true, force: true })
    // Another process can complete the same rename between the checks above
    // and this one; a non-empty target then fails with ENOTEMPTY or EEXIST.
    // Its verified bundle is as good as ours.
    const renamed = await fs.rename(tmp, root).then(
      () => true,
      (error: unknown) => {
        const code = error && typeof error === "object" && "code" in error ? error.code : undefined
        if (code !== "ENOTEMPTY" && code !== "EEXIST" && code !== "EPERM") throw error
        return false
      },
    )
    if (renamed) return root
    if (await verified(marker, input)) {
      await fs.rm(tmp, { recursive: true, force: true })
      return root
    }
    await fs.rm(tmp, { recursive: true, force: true })
    throw new Error("Bundled skill archive could not be installed: another installation left an incomplete bundle")
  }

  export async function root(): Promise<string | undefined> {
    const local = path.join(import.meta.dir, "../../skills")
    if (Installation.isLocal() && (await Filesystem.isDir(local))) return local

    const bundle = await generated()
    if (!bundle) {
      log.error("compiled release is missing its local skill bundle")
      return
    }

    return materialize({
      archive: bundle.SKILL_BUNDLE,
      digest: bundle.SKILL_BUNDLE_DIGEST,
      files: bundle.SKILL_BUNDLE_FILES,
      skills: bundle.SKILL_BUNDLE_SKILLS,
    })
  }
}
