import { describe, expect, test } from "bun:test"

const read = (name: string) => Bun.file(new URL(name, import.meta.url)).text()

describe("mobile compose and model sheets", () => {
  test("keeps the compact research actions visible without restoring legacy capability toggles", async () => {
    const [prompt, css] = await Promise.all([read("./prompt-input.tsx"), read("./prompt-input.css")])

    expect(prompt).not.toContain("data-mobile-compose-sheet")
    expect(prompt).not.toContain("data-mobile-compose-row")
    expect(prompt).toContain("onClick={attach}")
    expect(prompt).toContain('onClick={(event) => selectResearchEffort("normal", event.currentTarget)}')
    expect(prompt).toContain('onClick={(event) => selectResearchEffort("ultra", event.currentTarget)}')
    expect(prompt).toContain("<ModelSettingsPopover />")
    expect(prompt).not.toContain('aria-label="Composer mode"')
    expect(prompt).toContain('class="workspace-composer__send')
    expect(prompt).not.toContain('class="workspace-composer__effort"')
    expect(prompt).toContain('class="workspace-composer__research-tools"')
    expect(prompt).toContain('uiStore.openContext("kernels")')
    expect(prompt).toContain('<DialogSettings initial="skills" />')
    expect(prompt).toContain('<DialogSettings initial="connectors" />')
    expect(prompt).not.toContain('class="workspace-composer__overflow"')
    expect(prompt).not.toContain('aria-label="Research capabilities"')
    expect(prompt).not.toContain("toggleDelegation")
    expect(prompt).not.toContain("selectSpecialist")
    expect(prompt).not.toContain("selectReviewerModel")
    expect(prompt).not.toContain("delegatedSpecialist")
    expect(prompt).not.toContain("delegation:")
    expect(prompt).not.toContain("sdk.client.app.agents()")
    expect(prompt).not.toContain("local.agent.list()")
    expect(prompt).not.toContain("local.agent.set(")
    expect(prompt).not.toContain("agent.model")
    expect(prompt).not.toContain("<span>Memory</span>")
    expect(prompt).not.toContain("<span>Specialist</span>")
    expect(prompt).not.toContain('class="workspace-composer__compute-menu"')
    expect(prompt).not.toContain('"/settings/compute/provider/modal/enabled"')
    expect(prompt).not.toContain('"/settings/memory?scope=global"')
    expect(prompt).not.toContain("Review now")
    expect(prompt).not.toContain("Research agent")
    expect(prompt).not.toContain("General-purpose by default")
    expect(prompt).not.toContain('<Icon name="dot-grid" />')
    expect(prompt).not.toContain("Clear attachments")
    expect(prompt).not.toContain("Open Terminal")
    expect(prompt).not.toContain("Composer preferences")
    expect(prompt).not.toContain("Prompt history")
    expect(prompt.indexOf('class="workspace-composer__research-tools"')).toBeLessThan(
      prompt.indexOf('class="workspace-composer__actions'),
    )
    expect(prompt.indexOf("<ModelSettingsPopover />")).toBeGreaterThan(
      prompt.indexOf('class="workspace-composer__actions'),
    )
    expect(css).toContain("@media (max-width: 719px)")
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto")
    expect(css).toContain("@container conversation (max-width: 540px)")
    expect(css).toMatch(/@container conversation \(max-width: 540px\)[\s\S]*grid-template-columns: minmax\(0, 1fr\);/)
    expect(css).toContain("width: min(292px, calc(100cqw - 32px))")
    expect(css).toContain("overflow: visible")
    expect(css).not.toContain("overflow-x: auto")
    expect(css).toContain(".workspace-composer__research-effort-options")
    expect(css).not.toContain(".workspace-composer__effort")
    expect(css).toContain(".workspace-composer__research-tools")
    expect(css).toContain(".workspace-composer__research-tools-menu")
    expect(css).not.toContain(".workspace-composer__overflow")
    expect(css).not.toContain(".workspace-composer__compute-menu")
    expect(css).toContain("grid-template-columns: repeat(2, minmax(0, 1fr))")
    expect(css).not.toContain("mobile-compose-sheet")
  })

  test("uses a modal mobile settings surface without changing the desktop popover", async () => {
    const [settings, css] = await Promise.all([
      read("./model-settings-popover.tsx"),
      read("./model-settings-popover.css"),
    ])

    expect(settings).toContain("import { Popover as Kobalte }")
    expect(settings).toContain("modal={mobile()}")
    expect(settings).toContain('placement="top-end"')
    expect(settings).toContain("data-mobile-model-settings-overlay")
    expect(settings).toContain('aria-label="Close model options"')
    expect(settings).toContain("local.model.variant.set")
    expect(settings).toContain("local.model.tier.set")
    expect(settings).toContain("aria-label={`Thinking effort: ${props.value}`}")
    expect(settings).not.toContain("<span>Model effort</span>")
    expect(settings).toContain("groupModelRoutes")
    expect(css).toContain("[data-popper-positioner]:has(> [data-model-settings-popover])")
    expect(css).toContain("width: 100% !important")
    expect(css).toContain("transform: none !important")
    expect(css).toContain("inset: auto 0 0 !important")
    expect(css).toContain("border-radius: var(--radius-lg) var(--radius-lg) 0 0 !important")
    expect(css).toMatch(
      /@media \(pointer: coarse\)[\s\S]*\[data-model-control-group="label"\][\s\S]*height: 44px;[\s\S]*\[data-model-effort-chip\][\s\S]*min-height: 44px;/,
    )
  })

  test("renders model discovery as a scrollable edge-to-edge mobile dialog", async () => {
    const [picker, css] = await Promise.all([read("./dialog-select-model.tsx"), read("./dialog-select-model.css")])

    expect(picker).toContain('class="model-picker-sheet"')
    expect(picker).toContain('class="model-picker-sheet__list"')
    expect(picker).toContain("onSelect={() => dialog.close()}")
    expect(css).toContain("width: 100%")
    expect(css).toContain("border-radius: var(--radius-xl) var(--radius-xl) 0 0")
    expect(css).toContain("min-height: 63px")
    expect(css).toContain("font-size: 16px")
    expect(css).toContain("font-size: 13px")
    expect(css).toContain("overflow-y")
  })

  test("keeps desktop model discovery compact without changing the mobile sheet", async () => {
    const [picker, css] = await Promise.all([read("./dialog-select-model.tsx"), read("./dialog-select-model.css")])

    expect(picker).toContain('icon="sliders" class="model-picker-sheet__manage"')
    expect(picker).toContain("Open Customize for access, defaults, and composer models")
    expect(picker).not.toContain('class="model-picker-sheet__manage-inline"')
    expect(picker).not.toContain("[&_[data-slot=list-item]]:!py-2")
    expect(picker).not.toContain("[&_[data-slot=list-search]]:!p-2")
    expect(css).toContain("@media (min-width: 720px)")
    expect(css).toContain("width: min(calc(100vw - 32px), 480px)")
    expect(css).toContain("height: min(calc(100dvh - 48px), 440px)")
    expect(css).toContain("min-height: 38px")
    expect(css).toContain("min-height: 34px")
    expect(css).toContain("font-size: 13px")
    expect(css).toContain("font-size: 11px")
    expect(css).toContain(".model-picker-sheet__manage-copy")
    expect(picker).toContain("groupBy={category}")
    expect(picker).toContain('class="model-picker-sheet__pin"')
    expect(picker).not.toContain('aria-label="Model providers"')
    expect(css).toContain("@media (max-width: 719px)")
    expect(css).toContain("height: min(760px, calc(100dvh - 12px))")
  })
})
