import { describe, expect, test } from "bun:test"
import { existsSync, readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const source = (name: string) => readFileSync(fileURLToPath(new URL(name, import.meta.url)), "utf8")
const path = (name: string) => fileURLToPath(new URL(name, import.meta.url))

describe("model control surface", () => {
  test("keeps routing transport out while showing branded providers", () => {
    const files = ["./prompt-input.tsx", "./model-settings-popover.tsx"].map(source)

    for (const file of files) {
      expect(file).not.toContain("modelRoute")
      expect(file).not.toContain("via ")
      expect(file).not.toContain("OpenRouter")
    }
  })

  test("keeps the root model trigger compact with one adjacent effort control", () => {
    const composer = source("./prompt-input.tsx")
    expect(existsSync(path("./model-settings-popover.tsx"))).toBe(true)
    const settings = source("./model-settings-popover.tsx")
    const styles = source("./model-settings-popover.css")

    expect(composer).toContain("<ModelSettingsPopover />")
    expect(composer).not.toContain('data-action="model-variant-cycle"')
    expect(composer).not.toContain('data-action="model-tier-cycle"')
    expect(composer).not.toContain("Thinking ·")
    expect(settings).toContain("aria-label={`Model: ${control().trigger}`}")
    expect(settings).toContain("{control().trigger}")
    expect(settings).toContain("local.model.variant.list()")
    expect(composer).not.toContain('data-research-control="effort"')
    expect(composer).not.toContain('data-research-control="speed"')
    expect(settings).toContain("data-model-control-group")
    expect(settings).not.toContain("<span>Model effort</span>")
    expect(settings).toContain("control().effort")
    expect(settings).not.toContain('effort.current.id === "standard"')
    expect(settings).toContain("groupModelRoutes")
    expect(settings).not.toContain('kind="route"')
    expect(settings).not.toContain("routeAccess")
    expect(settings).toContain("preservedModelRoute")
    expect(settings).toContain('role="radiogroup"')
    expect(settings).toContain('role="radio"')
    expect(settings).toContain("aria-checked=")
    expect(settings).toContain("tabindex={quickTab() === choice.key ? 0 : -1}")
    expect(settings).toContain("tabindex={catalogTab() === choice.key ? 0 : -1}")
    expect(settings.match(/onKeyDown=\{focusModelRadio\}/g)).toHaveLength(2)
    expect(settings).toContain("onKeyDown={onMenuKeyDown}")
    expect(settings).not.toContain('window.addEventListener("keydown", dismiss, true)')
    expect(settings).not.toContain('window.removeEventListener("keydown", dismiss, true)')
    expect(settings.match(/<Kobalte(?:\s|>)/g)).toHaveLength(2)
    expect(settings.match(/<Kobalte\.Trigger/g)).toHaveLength(2)
    expect(settings).toContain('role="dialog"')
    expect(settings).toContain("data-model-popover-kind={props.kind}")
    expect(settings).toContain('class="model-settings-popover__header"')
    expect(settings).not.toContain("<span data-model-menu-label>Advanced</span>")
    expect(settings).not.toContain("Auto-accept permissions")
    expect(settings).toContain('<DialogSettings initial="models" />')
    expect(settings).not.toContain("<DialogManageModels />")
    expect(settings).toContain("model-settings-trigger--label")
    expect(settings).toContain('<Icon name="chevron-down"')
    expect(settings).not.toContain("⌄")
    expect(settings).toContain("data-model-quick")
    expect(settings).toContain("modelContext")
    expect(settings).not.toContain("access options")
    expect(settings).toContain("model.capabilities.reasoning")
    expect(settings).not.toContain("Balanced research, coding, and tool use")
    expect(settings).not.toContain("Deep analysis and scientific review")
    expect(settings).not.toContain("Long-context research and synthesis")
    expect(settings).toContain("More models")
    expect(settings).not.toContain('<p class="model-settings-heading">Models</p>')
    expect(settings).toContain("curateQuickModels")
    expect(settings).toContain("curateQuickModelRows")
    expect(settings).toContain("<For each={quickRows()}>")
    expect(settings).not.toContain("<For each={unavailable()}>")
    expect(settings).not.toContain("style={{ order:")
    expect(settings).not.toContain("rosterOrder")
    expect(settings).toContain("<ProviderIcon")
    expect(settings).not.toContain("RECOMMENDED_MODELS")
    expect(settings).toContain("Find a model or provider")
    expect(settings).toContain("Manage models")
    expect(settings).not.toContain("data-model-source-label")
    expect(settings).toContain("data-model-menu-value")
    expect(styles).toContain("width: min(344px, calc(100vw - 24px))")
    expect(settings).toContain('<Show when={view() === "root"}>')
    expect(styles).not.toContain("width: min(320px, calc(100vw - 24px))")
    expect(styles).toContain("[data-model-settings-layout] {\n    display: block")
    expect(styles).not.toContain("grid-template-columns: minmax(0, 272px) minmax(0, 304px)")
    expect(styles).toContain("overflow-y: auto")
    expect(styles).toMatch(
      /\[data-model-popover-kind="effort"\] \.model-settings-popover__body\s*\{[^}]*overflow-y: auto;[^}]*overscroll-behavior: contain;/s,
    )
    expect(styles).not.toMatch(
      /\[data-model-popover-kind="effort"\] \.model-settings-popover__body\s*\{[^}]*overflow: visible;/s,
    )
    expect(styles).toContain("[data-model-effort-chip] strong")
    expect(styles).toContain("line-height: 20px")
    expect(styles).toContain('[data-model-options-compact] [role="radiogroup"] {\n  display: grid;')
    expect(styles).toMatch(
      /\[data-model-settings-popover\] \[data-model-options-compact\] \.model-settings-row:hover,[\s\S]*background: var\(--model-control-hover\);/,
    )
    expect(styles).toContain("min-height: 58px")
    expect(styles).toContain("font-size: 14px")
    expect(styles).toContain("color: var(--text-interactive-base)")
    expect(styles).not.toContain("--model-control-surface: #30302d")
    expect(styles).toContain("font-family: var(")
    expect(styles).toContain("font-optical-sizing: auto")
    expect(styles).toContain("font-synthesis: none")
    expect(styles).toContain("-webkit-font-smoothing: antialiased")
    expect(styles).toContain("font-weight: var(--font-weight-regular)")
    expect(styles).not.toMatch(/font-weight:\s*(?:400|450|500|550|600|700)/)
    expect(styles).not.toContain("text-transform:")

    const triggerRule = styles.match(/\[data-model-settings-trigger-style="label"\]\s*\{([^}]*)\}/s)?.[1] ?? ""
    expect(triggerRule).toContain("border: 0")
    expect(triggerRule).toContain("gap: 7px")
    expect(triggerRule).toContain("padding: 0 8px")
    expect(triggerRule).toContain("font-size: 13px")
    expect(triggerRule).toContain("line-height: 1")
    expect(settings).toContain("data-model-effort-chip")

    const rowRule = styles.match(/\[data-model-settings-popover\] \.model-settings-row\s*\{([^}]*)\}/s)?.[1] ?? ""
    expect(rowRule).toContain("gap: 10px")
    expect(rowRule).toContain("padding: 5px 9px")
    expect(rowRule).toContain("font-size: 13px")
    expect(rowRule).toContain("line-height: 18px")
    expect(styles).toContain("min-height: 44px")
    expect(styles).toContain("font-size: 11px")
    expect(styles).toContain("line-height: 15px")

    const model = settings.indexOf('data-model-menu-row="model"')
    const quick = settings.indexOf("data-model-quick")
    const effort = settings.indexOf('kind="effort"')
    const fast = settings.indexOf("data-model-fast-toggle")

    expect(model).toBeGreaterThan(-1)
    expect(quick).toBeGreaterThan(-1)
    expect(effort).toBeGreaterThan(-1)
    expect(fast).toBeGreaterThan(-1)
    expect(settings).not.toContain('kind="speed"')
    expect(settings).not.toContain("Available through")
    expect(settings).toContain("exactRouteFastMode(current(), local.model.tier.current())")
    expect(settings).toContain("fast={fast()}")
    expect(settings).toContain("onEffortSelect={(id) => local.model.variant.set(id)}")
    expect(settings).toContain("onTierSelect={(id) => local.model.tier.set(id)}")
  })
})
