import { expect, test } from "bun:test"

const source = await Bun.file(new URL("./CommandPalette.tsx", import.meta.url)).text()
const styles = await Bun.file(new URL("./CommandPalette.css", import.meta.url)).text()
const shell = await Bun.file(new URL("../styles/atlas.css", import.meta.url)).text()
const commands = await Bun.file(new URL("../context/command.tsx", import.meta.url)).text()
const home = await Bun.file(new URL("../pages/home.tsx", import.meta.url)).text()
const session = await Bun.file(new URL("../pages/session.tsx", import.meta.url)).text()

test("uses the shared modal foundation for a stable, focus-contained palette", async () => {
  expect(source).toContain('import { Dialog as Kobalte } from "@kobalte/core/dialog"')
  expect(source).toContain('import "./CommandPalette.css"')
  expect(source).toContain("<Kobalte.Content")
  expect(source).toContain("<Kobalte.Overlay")
  expect(source).toContain("onOpenAutoFocus")
  expect(source).toContain("onCloseAutoFocus")
  expect(source).toContain("if (restoreFocus?.isConnected) restoreFocus.focus()")
  expect(source).toContain('class="atlas-modal command-palette"')
  expect(source).not.toContain('class="atlas-modal atlas-fade-in command-palette"')
  expect(source).not.toContain("conversation-center")
  expect(styles).toContain(".command-palette")
  expect(styles).toContain("width: min(680px, calc(100vw - 24px))")
  expect(styles).toContain("top: var(--command-palette-top)")
  expect(styles).toContain("max-height: min(640px, calc(100dvh - var(--command-palette-top) - 12px))")
  expect(styles).toContain("transform: translate(-50%, 0)")
  expect(styles).toContain("@keyframes command-palette-in")
  expect(shell).not.toContain("command-palette-in")
  expect(shell).not.toContain(".command-palette")
  expect(source).toContain('role="dialog"')
  expect(source).toContain('aria-modal="true"')
  expect(source).toContain('aria-labelledby="command-palette-title"')
  expect(source).toContain('aria-describedby="command-palette-description"')
  expect(source).not.toContain('window.addEventListener("keydown"')
})

test("renders a quiet project-search header with responsive, overflow-safe styling", () => {
  expect(source).toContain("Search this project")
  expect(source).toContain("Search sessions, transcript messages, workspace files, artifacts, and project actions.")
  expect(source).toContain("Search sessions, messages, files, and actions…")
  expect(source).toContain('class="command-palette__scope"')
  expect(source).toContain('class="command-palette__search"')
  expect(source).toContain("data-focus-frame")
  expect(source).toContain('class="command-palette__sr-only"')
  expect(source).not.toContain("style={{")
  expect(styles).toContain("min-height: 0")
  expect(styles).toContain("overflow-x: clip")
  expect(styles).toContain("overflow-y: auto")
  expect(styles).toContain("grid-template-columns: 22px minmax(0, 1fr) auto")
  expect(styles).toContain("box-shadow: none")
  expect(styles).not.toContain("box-shadow: inset 0 0 0 1px")
  expect(styles).toContain("@container command-palette (max-width: 420px)")
  expect(styles).toContain("width: calc(100vw - 16px)")
})

test("uses restrained semantic typography, radii, and usable hit targets", () => {
  expect(styles).toContain("font-weight: var(--font-weight-regular)")
  expect(styles).toContain("font-weight: var(--font-weight-medium)")
  expect(styles).not.toMatch(/font-weight:\s*(?:[1-9]00|bold|normal)/)
  expect(styles).toContain("border-radius: var(--atlas-radius-md)")
  expect(styles).toContain("border-radius: var(--atlas-radius-xs)")
  expect(styles).not.toMatch(/border-radius:\s*(?:7|8|16|999)px/)
  expect(styles).toContain("border: 1px solid var(--color-border)")
  expect(styles).toContain("border-bottom: 1px solid var(--border-weak-base)")
  expect(styles).toContain("background: var(--color-surface-solid)")
  expect(styles).not.toContain("color-mix(")
  expect(styles).not.toMatch(/border(?:-(?:top|right|bottom|left))?:.*color-mix/)
  expect(styles).toContain("min-height: 44px")
  expect(styles).toContain("@media (pointer: coarse)")
  expect(styles).toContain("min-height: 48px")
})

test("removes decorative hierarchy that made search feel like a dashboard", () => {
  expect(source).not.toContain("command-palette__heading-copy")
  expect(source).not.toContain("command-palette__group-note")
  expect(source).not.toContain("command-palette__group-count")
  expect(source).not.toContain("command-palette__option-enter")
  expect(source).toContain('class="command-palette__footer" aria-hidden="true"')
  expect(styles).not.toContain("scrollbar-gutter")
  expect(styles).toContain("backdrop-filter: none")
})

test("renders registered commands instead of maintaining a shadow action list", () => {
  expect(source).toContain("const command = useCommand()")
  expect(source).toContain("return command.options.flatMap")
  expect(source).toContain('command.trigger(option.id, "palette")')
  expect(source).not.toContain('id: "open-files"')
  expect(source).not.toContain('id: "compute-monitor"')
  expect(source).not.toContain("DialogSettings")
  expect(source).not.toContain("FolderPicker")
  expect(source).not.toContain("lite: true")
  expect(source).toContain("pendingRun = item.run")
  expect(source).toContain("if (run) queueMicrotask(run)")
  expect(source).toContain("command.keybinds(false)")
  expect(source).toContain("command.keybinds(true)")
})

test("registers route-owned actions and removes the dead file.open palette path", () => {
  expect(home).toContain('id: "project.create"')
  expect(home).not.toContain('id: "project.import"')
  expect(home).toContain('id: "server.switch"')
  expect(session).toContain('id: "session.new"')
  expect(session).toContain('id: "project.files"')
  expect(session).toContain('id: "project.compute"')
  expect(session).toContain('id: "settings.open"')
  expect(session).toContain('id: "documentation.open"')
  expect(commands).not.toContain('run("file.open", "palette")')
  expect(commands).not.toContain("showPalette")
})

test("wires /search through the project-scoped request helper with debounce and cancellation", () => {
  expect(source).toContain('requestProjectSearch(() => request("/search", { signal: controller.signal }, { q }))')
  expect(source).toContain("createProjectRequest({")
  expect(source).toContain("const DEBOUNCE = 250")
  expect(source).toContain("setTimeout(") // debounced fetch
  expect(source).toContain("new AbortController()")
  expect(source).toContain("inflight?.abort()") // stale requests cancelled
  expect(source).toMatch(
    /if \(!scoped\)[\s\S]*setHits\(undefined\)[\s\S]*setHits\(undefined\)[\s\S]*setSearching\(true\)/,
  )
  expect(source).toContain("q.length >= 2") // no fetch below the server minimum
  expect(source).toContain("resolveProjectRoute(params.dir, sync.data.project)")
  expect(source).toContain("requestProjectSearch")
  expect(source).toContain("setSearchError(true)")
  expect(source).toContain("setSearchRetry((value) => value + 1)")
})

test("renders the four search groups and routes selection correctly", () => {
  expect(source).toContain('category: "Sessions"')
  expect(source).toContain('category: "Messages"')
  expect(source).toContain('category: "Files"')
  expect(source).toContain('category: "Artifacts"')
  expect(source).toContain("projectHref(scope.project, scope.directory, s.id)")
  expect(source).toContain("projectHref(scope.project, scope.directory, m.sessionID)")
  expect(source).toContain("reveal(m.messageID)")
  expect(source).toContain("data-message-id") // transcript anchor for scroll-to-message
  expect(source).toContain("uiStore.openFile(scope.directory, f.path)")
  expect(source).toContain("uiStore.openFile(scope.directory, a.path)")
  expect(source).not.toContain("groupNote(")
  expect(source).not.toContain("group.cmds.length")
})

test("keeps project search local and shows recent sessions before registered commands", () => {
  expect(source).toContain("if (active()) return []")
  expect(source).toContain("sync.data.project.map")
  expect(source).toContain('category: "Recent sessions"')
  expect(source).toContain("const available = [...registered(), ...projects()]")
  expect(source).toContain(": [...recent(), ...available]")
})

test("keeps the flat selection model across search groups", () => {
  expect(source).toContain("return [...base, ...results()]")
  expect(source).toContain("if (q && active()) return [...results(), ...base]")
})

test("updates keyboard highlight state without animating between rows", () => {
  expect(source).toContain("if (event.target !== inputRef) return")
  expect(source).toContain('event.key === "ArrowDown"')
  expect(source).toContain('event.key === "ArrowUp"')
  expect(source).not.toContain('event.key === "Home"')
  expect(source).not.toContain('event.key === "End"')
  expect(source).not.toContain('transition: "background')
  expect(source).toContain('scrollIntoView({ block: "nearest" })')
  expect(styles).not.toMatch(/\.command-palette__option\s*\{[^}]*transition:/s)
})

test("exposes a combobox/listbox relationship and active option", () => {
  expect(source).toContain('role="combobox"')
  expect(source).toContain('aria-controls="command-palette-results"')
  expect(source).toContain('role="listbox"')
  expect(source).toContain('role="option"')
  expect(source).toContain('tabindex="-1"')
  expect(source).toContain("aria-activedescendant")
  expect(source).toContain("aria-selected={highlighted() === idx()}")
})

test("labels the palette as local search without overpromising", () => {
  expect(source).toContain("Search sessions, messages, files, and actions…")
  expect(source).toContain("Local project search")
  expect(source).not.toContain("semantic")
})

test("shows a searching row in flight and no-matches only after completion", () => {
  expect(source).toContain("Searching…")
  expect(source).toContain("No matches")
  expect(source).toContain("!searching() && !searchError() && !short() && filtered().length === 0")
  expect(source).toContain("Type one more character")
  expect(source).toContain("Search unavailable")
  expect(source).toContain("Project content could not be searched")
  expect(source).toContain("Retry")
  expect(source).toContain('aria-live="polite"')
})
